use serde::Deserialize;
use std::{collections::BTreeMap, env, fs, path::PathBuf};

#[derive(Debug, Deserialize)]
struct Config {
    general: GeneralConfig,
    #[allow(dead_code)]
    display: DisplayConfig,
    input: InputConfig,
    scroll: ScrollConfig,
    profiles: BTreeMap<String, ProfileConfig>,
    battery: BatteryConfig,
}

#[derive(Debug, Deserialize)]
struct GeneralConfig {
    default_profile: String,
    profile_order: Vec<String>,
}

#[derive(Debug, Deserialize)]
struct DisplayConfig {
    timeout_seconds: u64,
    brightness: u8,
    show_battery: bool,
    show_connection: bool,
    show_profile: bool,
}

#[derive(Debug, Clone, Deserialize)]
struct InputConfig {
    combo_window_ms: u64,
    tap_max_ms: u64,
    default_hold_ms: u64,
    button_a: ButtonInputConfig,
    button_b: ButtonInputConfig,
    joy_click: ButtonInputConfig,
    #[serde(default)]
    combo: Vec<ComboConfig>,
}

#[derive(Debug, Clone, Deserialize)]
struct ButtonInputConfig {
    tap: Option<String>,
    hold: Option<String>,
    hold_ms: Option<u64>,
    hold_joy: Option<String>,
}

#[derive(Debug, Clone, Deserialize)]
struct ComboConfig {
    buttons: Vec<String>,
    action: String,
    hold_ms: Option<u64>,
}

#[derive(Debug, Clone, Deserialize)]
struct ScrollConfig {
    dead_zone: i32,
    speed: i32,
    horizontal: bool,
    invert_vertical: bool,
    invert_horizontal: bool,
}

#[derive(Debug, Deserialize)]
struct ProfileConfig {
    label: String,
    orientation: String,
    mouse: MouseConfig,
    input: Option<InputConfig>,
    scroll: Option<ScrollConfig>,
}

#[derive(Debug, Deserialize)]
struct MouseConfig {
    poll_hz: u64,
    dead_zone: i32,
    base_speed_px_per_sec: f64,
    max_speed_px_per_sec: f64,
    gain_rise_per_sec: f64,
    gain_fall_per_sec: f64,
    curve_weight: f64,
    smoothing: f64,
    invert_x: bool,
    invert_y: bool,
}

#[derive(Debug, Deserialize)]
struct BatteryConfig {
    raw_empty: u16,
    raw_full: u16,
    empty_mv: u16,
    full_mv: u16,
    poll_seconds: u64,
}

fn main() {
    // esp-generate の Xtensa 用処理
    linker_be_nice();
    check_xtensa_linker_available();

    // presenter.toml -> Rust 定数
    generate_presenter_config();

    // 重要:
    // linkall.x は最後の linker script にする．
    println!("cargo:rustc-link-arg=-Tlinkall.x");
}

fn generate_presenter_config() {
    println!("cargo:rerun-if-changed=presenter.toml");

    let source = fs::read_to_string("presenter.toml").expect("failed to read presenter.toml");
    let config: Config = toml::from_str(&source).expect("invalid presenter.toml");

    validate_display(&config.display);
    validate_battery(&config.battery);
    validate_input(&config.input);
    validate_scroll(&config.scroll, "scroll");
    validate_profiles(&config);

    let default_profile_index = config
        .general
        .profile_order
        .iter()
        .position(|name| name == &config.general.default_profile)
        .expect("general.default_profile must exist in general.profile_order");

    let mut combo_statics = String::new();
    let mut profile_entries = Vec::new();

    for (index, name) in config.general.profile_order.iter().enumerate() {
        let profile = config
            .profiles
            .get(name)
            .expect("profile_order entry missing");
        let input = profile.input.as_ref().unwrap_or(&config.input);
        let scroll = profile.scroll.as_ref().unwrap_or(&config.scroll);
        let mouse = &profile.mouse;
        let combos_name = format!("PROFILE_{index}_COMBOS");

        combo_statics.push_str(&format!(
            "static {combos_name}: [ComboConfig; {combo_count}] = [\n{combos}\n];\n\n",
            combo_count = input.combo.len(),
            combos = render_combos(&input.combo),
        ));

        profile_entries.push(format!(
            r#"    ProfileConfig {{
        name: {name:?},
        label: {label:?},
        orientation: {orientation},
        mouse: {mouse},
        scroll: {scroll},
        input: {input},
    }}"#,
            name = name,
            label = profile.label,
            orientation = render_orientation(&profile.orientation),
            mouse = render_mouse(mouse),
            scroll = render_scroll(scroll),
            input = render_input(input, &combos_name),
        ));
    }

    let generated = format!(
        r#"
// This file is automatically generated by build.rs.
// Do not edit manually.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Orientation {{
    Normal,
    Right,
    Inverted,
    Left,
}}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Action {{
    KeyboardKey(u8),
    MouseButton(u8),
    ScrollMode,
    NextProfile,
    None,
}}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ButtonInputConfig {{
    pub tap: Action,
    pub hold: Action,
    pub hold_ms: u64,
    pub hold_joy: Action,
}}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ComboConfig {{
    pub buttons: u8,
    pub action: Action,
    pub hold_ms: u64,
}}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct InputConfig {{
    pub combo_window_ms: u64,
    pub tap_max_ms: u64,
    pub default_hold_ms: u64,
    pub button_a: ButtonInputConfig,
    pub button_b: ButtonInputConfig,
    pub joy_click: ButtonInputConfig,
    pub combos: &'static [ComboConfig],
}}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MouseConfig {{
    pub poll_hz: i64,
    pub poll_interval_us: u64,
    pub dead_zone: i32,
    pub base_speed_px_per_sec: i32,
    pub max_speed_px_per_sec: i32,
    pub gain_rise_q15_per_sec: i32,
    pub gain_fall_q15_per_sec: i32,
    pub curve_weight_q15: i32,
    pub smoothing_q15: i32,
    pub invert_x: bool,
    pub invert_y: bool,
}}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ScrollConfig {{
    pub dead_zone: i32,
    pub speed: i32,
    pub horizontal: bool,
    pub invert_vertical: bool,
    pub invert_horizontal: bool,
}}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ProfileConfig {{
    pub name: &'static str,
    pub label: &'static str,
    pub orientation: Orientation,
    pub mouse: MouseConfig,
    pub scroll: ScrollConfig,
    pub input: InputConfig,
}}

pub const BUTTON_A_BIT: u8 = 0x01;
pub const BUTTON_B_BIT: u8 = 0x02;
pub const JOY_CLICK_BIT: u8 = 0x04;

pub const MOUSE_BUTTON_LEFT: u8 = 0x01;
pub const MOUSE_BUTTON_RIGHT: u8 = 0x02;
pub const MOUSE_BUTTON_MIDDLE: u8 = 0x04;

{combo_statics}pub const PROFILE_COUNT: usize = {profile_count};
pub const DEFAULT_PROFILE_INDEX: usize = {default_profile_index};
pub static PROFILES: [ProfileConfig; PROFILE_COUNT] = [
{profiles}
];

pub const DISPLAY_TIMEOUT_SECONDS: u64 = {display_timeout_seconds};
pub const DISPLAY_BRIGHTNESS: u8 = {display_brightness};

pub const BATTERY_RAW_EMPTY: u16 = {battery_raw_empty};
pub const BATTERY_RAW_FULL: u16 = {battery_raw_full};

pub const BATTERY_EMPTY_MV: u16 = {battery_empty_mv};
pub const BATTERY_FULL_MV: u16 = {battery_full_mv};

pub const BATTERY_POLL_SECONDS: u64 = {battery_poll_seconds};
"#,
        combo_statics = combo_statics,
        profile_count = config.general.profile_order.len(),
        default_profile_index = default_profile_index,
        profiles = profile_entries.join(",\n"),
        display_timeout_seconds = config.display.timeout_seconds,
        display_brightness = config.display.brightness,
        battery_raw_empty = config.battery.raw_empty,
        battery_raw_full = config.battery.raw_full,
        battery_empty_mv = config.battery.empty_mv,
        battery_full_mv = config.battery.full_mv,
        battery_poll_seconds = config.battery.poll_seconds,
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is not set"));
    let output = out_dir.join("presenter_config.rs");

    fs::write(&output, generated).expect("failed to write presenter_config.rs");

    println!(
        "cargo:warning=generated presenter config: {}",
        output.display()
    );
}

fn render_mouse(mouse: &MouseConfig) -> String {
    format!(
        "MouseConfig {{ poll_hz: {poll_hz}, poll_interval_us: {interval_us}, dead_zone: {dead_zone}, base_speed_px_per_sec: {base_speed}, max_speed_px_per_sec: {max_speed}, gain_rise_q15_per_sec: {gain_rise_q15}, gain_fall_q15_per_sec: {gain_fall_q15}, curve_weight_q15: {curve_weight_q15}, smoothing_q15: {smoothing_q15}, invert_x: {invert_x}, invert_y: {invert_y} }}",
        poll_hz = mouse.poll_hz,
        interval_us = 1_000_000 / mouse.poll_hz,
        dead_zone = mouse.dead_zone,
        base_speed = mouse.base_speed_px_per_sec.round() as i32,
        max_speed = mouse.max_speed_px_per_sec.round() as i32,
        gain_rise_q15 = (mouse.gain_rise_per_sec * 32768.0).round() as i32,
        gain_fall_q15 = (mouse.gain_fall_per_sec * 32768.0).round() as i32,
        curve_weight_q15 = (mouse.curve_weight * 32768.0).round() as i32,
        smoothing_q15 = (mouse.smoothing * 32768.0).round() as i32,
        invert_x = mouse.invert_x,
        invert_y = mouse.invert_y,
    )
}

fn render_scroll(scroll: &ScrollConfig) -> String {
    format!(
        "ScrollConfig {{ dead_zone: {dead_zone}, speed: {speed}, horizontal: {horizontal}, invert_vertical: {invert_vertical}, invert_horizontal: {invert_horizontal} }}",
        dead_zone = scroll.dead_zone,
        speed = scroll.speed,
        horizontal = scroll.horizontal,
        invert_vertical = scroll.invert_vertical,
        invert_horizontal = scroll.invert_horizontal,
    )
}

fn render_input(input: &InputConfig, combos_name: &str) -> String {
    format!(
        "InputConfig {{ combo_window_ms: {combo_window_ms}, tap_max_ms: {tap_max_ms}, default_hold_ms: {default_hold_ms}, button_a: {button_a}, button_b: {button_b}, joy_click: {joy_click}, combos: &{combos_name} }}",
        combo_window_ms = input.combo_window_ms,
        tap_max_ms = input.tap_max_ms,
        default_hold_ms = input.default_hold_ms,
        button_a = render_button_input(&input.button_a, input.default_hold_ms),
        button_b = render_button_input(&input.button_b, input.default_hold_ms),
        joy_click = render_button_input(&input.joy_click, input.default_hold_ms),
    )
}

fn render_button_input(input: &ButtonInputConfig, default_hold_ms: u64) -> String {
    format!(
        "ButtonInputConfig {{ tap: {tap}, hold: {hold}, hold_ms: {hold_ms}, hold_joy: {hold_joy} }}",
        tap = render_optional_action(input.tap.as_deref()),
        hold = render_optional_action(input.hold.as_deref()),
        hold_ms = input.hold_ms.unwrap_or(default_hold_ms),
        hold_joy = render_optional_action(input.hold_joy.as_deref()),
    )
}

fn render_combos(combos: &[ComboConfig]) -> String {
    combos
        .iter()
        .map(|combo| {
            format!(
                "    ComboConfig {{ buttons: {buttons}, action: {action}, hold_ms: {hold_ms} }},",
                buttons = combo_button_mask(&combo.buttons),
                action = render_action(&combo.action),
                hold_ms = combo.hold_ms.unwrap_or(0),
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn render_orientation(value: &str) -> &'static str {
    match value {
        "normal" => "Orientation::Normal",
        "right" => "Orientation::Right",
        "inverted" => "Orientation::Inverted",
        "left" => "Orientation::Left",
        other => panic!("unknown orientation: {other}"),
    }
}

fn render_optional_action(action: Option<&str>) -> String {
    action
        .map(render_action)
        .unwrap_or_else(|| "Action::None".to_string())
}

fn render_action(action: &str) -> String {
    match action {
        "RightArrow" => "Action::KeyboardKey(0x4f)".to_string(),
        "LeftArrow" => "Action::KeyboardKey(0x50)".to_string(),
        "PageDown" => "Action::KeyboardKey(0x4e)".to_string(),
        "PageUp" => "Action::KeyboardKey(0x4b)".to_string(),
        "Space" => "Action::KeyboardKey(0x2c)".to_string(),
        "Enter" => "Action::KeyboardKey(0x28)".to_string(),
        "Escape" => "Action::KeyboardKey(0x29)".to_string(),
        "F5" => "Action::KeyboardKey(0x3e)".to_string(),
        "MouseLeft" => "Action::MouseButton(MOUSE_BUTTON_LEFT)".to_string(),
        "MouseRight" => "Action::MouseButton(MOUSE_BUTTON_RIGHT)".to_string(),
        "MouseMiddle" => "Action::MouseButton(MOUSE_BUTTON_MIDDLE)".to_string(),
        "Scroll" => "Action::ScrollMode".to_string(),
        "NextProfile" => "Action::NextProfile".to_string(),
        "None" => "Action::None".to_string(),
        other => panic!("unknown action: {other}"),
    }
}

fn combo_button_mask(buttons: &[String]) -> String {
    let mut mask = 0u8;

    for button in buttons {
        mask |= match button.as_str() {
            "button_a" => 0x01,
            "button_b" => 0x02,
            "joy_click" => 0x04,
            other => panic!("unknown combo button: {other}"),
        };
    }

    format!("{mask:#04x}")
}

fn validate_profiles(config: &Config) {
    assert!(
        !config.general.profile_order.is_empty(),
        "general.profile_order must not be empty"
    );

    assert!(
        config
            .profiles
            .contains_key(&config.general.default_profile),
        "general.default_profile must exist in profiles"
    );

    for name in &config.general.profile_order {
        let profile = config
            .profiles
            .get(name)
            .unwrap_or_else(|| panic!("profile_order entry `{name}` is not defined in profiles"));

        validate_orientation(
            &profile.orientation,
            &format!("profiles.{name}.orientation"),
        );
        validate_mouse(&profile.mouse, &format!("profiles.{name}.mouse"));

        if let Some(input) = &profile.input {
            validate_input(input);
        }

        if let Some(scroll) = &profile.scroll {
            validate_scroll(scroll, &format!("profiles.{name}.scroll"));
        }
    }
}

fn validate_display(display: &DisplayConfig) {
    assert!(
        display.timeout_seconds > 0,
        "display.timeout_seconds must be greater than 0"
    );

    assert!(
        display.brightness <= 100,
        "display.brightness must be in 0..=100"
    );

    let _ = (
        display.show_battery,
        display.show_connection,
        display.show_profile,
    );
}

fn validate_battery(battery: &BatteryConfig) {
    assert!(
        battery.raw_full > battery.raw_empty,
        "battery.raw_full must be greater than battery.raw_empty"
    );

    assert!(
        battery.full_mv > battery.empty_mv,
        "battery.full_mv must be greater than battery.empty_mv"
    );

    assert!(
        battery.poll_seconds > 0,
        "battery.poll_seconds must be greater than 0"
    );
}

fn validate_input(input: &InputConfig) {
    assert!(
        input.combo_window_ms > 0,
        "input.combo_window_ms must be greater than 0"
    );

    assert!(
        input.tap_max_ms > 0,
        "input.tap_max_ms must be greater than 0"
    );

    assert!(
        input.default_hold_ms > 0,
        "input.default_hold_ms must be greater than 0"
    );

    validate_button_input(&input.button_a, "input.button_a");
    validate_button_input(&input.button_b, "input.button_b");
    validate_button_input(&input.joy_click, "input.joy_click");

    for combo in &input.combo {
        assert!(
            combo.buttons.len() >= 2,
            "combo must contain at least 2 buttons"
        );

        for button in &combo.buttons {
            validate_button_id(button);
        }

        validate_action(&combo.action);

        if let Some(hold_ms) = combo.hold_ms {
            assert!(hold_ms > 0, "combo.hold_ms must be greater than 0");
        }
    }
}

fn validate_button_input(input: &ButtonInputConfig, name: &str) {
    if let Some(action) = &input.tap {
        validate_action(action);
    }

    if let Some(action) = &input.hold {
        validate_action(action);
    }

    if let Some(hold_ms) = input.hold_ms {
        assert!(hold_ms > 0, "{name}.hold_ms must be greater than 0");
    }

    if let Some(action) = &input.hold_joy {
        validate_action(action);
    }
}

fn validate_scroll(scroll: &ScrollConfig, name: &str) {
    assert!(
        (0..127).contains(&scroll.dead_zone),
        "{name}.dead_zone must be in 0..127"
    );

    assert!(scroll.speed > 0, "{name}.speed must be greater than 0");
}

fn validate_mouse(mouse: &MouseConfig, name: &str) {
    assert!(mouse.poll_hz > 0, "{name}.poll_hz must be greater than 0");

    assert!(
        (0..127).contains(&mouse.dead_zone),
        "{name}.dead_zone must be in 0..127"
    );

    assert!(
        mouse.base_speed_px_per_sec > 0.0,
        "{name}.base_speed_px_per_sec must be greater than 0"
    );

    assert!(
        mouse.max_speed_px_per_sec >= mouse.base_speed_px_per_sec,
        "{name}.max_speed_px_per_sec must be greater than or equal to base speed"
    );

    assert!(
        mouse.gain_rise_per_sec > 0.0,
        "{name}.gain_rise_per_sec must be greater than 0"
    );

    assert!(
        mouse.gain_fall_per_sec > 0.0,
        "{name}.gain_fall_per_sec must be greater than 0"
    );

    assert!(
        (0.0..=1.0).contains(&mouse.curve_weight),
        "{name}.curve_weight must be in 0.0..=1.0"
    );

    assert!(
        (0.0..=1.0).contains(&mouse.smoothing),
        "{name}.smoothing must be in 0.0..=1.0"
    );
}

fn validate_orientation(value: &str, name: &str) {
    match value {
        "normal" | "right" | "inverted" | "left" => {}
        other => panic!("unknown {name}: {other}"),
    }
}

fn validate_button_id(value: &str) {
    match value {
        "button_a" | "button_b" | "joy_click" => {}
        other => panic!("unknown combo button: {other}"),
    }
}

fn validate_action(value: &str) {
    match value {
        "RightArrow" | "LeftArrow" | "PageDown" | "PageUp" | "Space" | "Enter" | "Escape"
        | "F5" | "MouseLeft" | "MouseRight" | "MouseMiddle" | "Scroll" | "NextProfile" | "None" => {
        }
        other => panic!("unknown action: {other}"),
    }
}

// -----------------------------------------------------------------------------
// ESP32 / Xtensa linker support
//
// The functions below are based on the esp-generate Xtensa project template.
// -----------------------------------------------------------------------------

#[cfg(unix)]
fn check_xtensa_linker_available() {
    println!("cargo:rerun-if-env-changed=PATH");

    let target = env::var("TARGET").unwrap_or_default();

    println!(
        "cargo:rerun-if-env-changed={}",
        cargo_linker_env_var(&target)
    );

    let linker = xtensa_linker(&target);

    let error = match std::process::Command::new(&linker)
        .arg("--version")
        .output()
    {
        Ok(_) => return,
        Err(error) => error,
    };

    let export_file = env::var("HOME")
        .map(|home| format!("{home}/export-esp.sh"))
        .unwrap_or_else(|_| "$HOME/export-esp.sh".to_string());

    panic!(
        "Xtensa linker `{linker}` was not found in PATH \
         or could not be executed: {error}.\n\n\
         Xtensa targets on Unix require espup's environment \
         export file to be sourced before building.\n\
         Try: `source {export_file}`\n\n\
         If the export file does not exist, \
         run `espup install` first."
    );
}

#[cfg(not(unix))]
fn check_xtensa_linker_available() {}

#[cfg(unix)]
fn xtensa_linker(target: &str) -> String {
    if let Some(linker) = cargo_configured_linker(target) {
        return linker;
    }

    target
        .strip_prefix("xtensa-")
        .and_then(|target| target.strip_suffix("-none-elf"))
        .map(|chip| format!("xtensa-{chip}-elf-gcc"))
        .unwrap_or_else(|| "xtensa-esp32-elf-gcc".to_string())
}

#[cfg(unix)]
fn cargo_configured_linker(target: &str) -> Option<String> {
    env::var(cargo_linker_env_var(target)).ok()
}

#[cfg(unix)]
fn cargo_linker_env_var(target: &str) -> String {
    let target = target.replace('-', "_").to_ascii_uppercase();

    format!("CARGO_TARGET_{target}_LINKER")
}

fn linker_be_nice() {
    let args: Vec<String> = env::args().collect();

    if args.len() > 2 {
        let kind = &args[1];
        let what = &args[2];

        match kind.as_str() {
            "undefined-symbol" => match what.as_str() {
                "_stack_start" => {
                    eprintln!();
                    eprintln!("linkall.x may be missing");
                    eprintln!();
                }

                what if what.starts_with("esp_rtos_") => {
                    eprintln!();
                    eprintln!(
                        "esp-radio has no scheduler enabled. \
                             Make sure esp-rtos is initialized."
                    );
                    eprintln!();
                }

                "free"
                | "malloc"
                | "calloc"
                | "get_free_internal_heap_size"
                | "malloc_internal"
                | "realloc_internal"
                | "calloc_internal"
                | "free_internal" => {
                    eprintln!();
                    eprintln!(
                        "esp-alloc may be missing \
                             or incorrectly configured"
                    );
                    eprintln!();
                }

                _ => {}
            },

            _ => {
                std::process::exit(1);
            }
        }

        std::process::exit(0);
    }

    // Xtensa linker の診断をこの build.rs へ戻す．
    println!(
        "cargo:rustc-link-arg=-Wl,--error-handling-script={}",
        env::current_exe().unwrap().display()
    );
}
