use serde::Deserialize;
use std::{env, fs, path::PathBuf};

#[derive(Debug, Deserialize)]
struct Config {
    mouse: MouseConfig,
    keymap: KeymapConfig,
    battery: BatteryConfig,
}

#[derive(Debug, Deserialize)]
struct MouseConfig {
    poll_hz: u64,
    dead_zone: i32,
    base_speed_px_per_sec: f64,
    max_speed_px_per_sec: f64,
    gain_rise_per_sec: f64,
    gain_fall_per_sec: f64,
    curve_weight: f64,
    smoothing: f64,
    invert_x: bool,
    invert_y: bool,
}

#[derive(Debug, Deserialize)]
struct KeymapConfig {
    button_a: String,
    button_b: String,
}

#[derive(Debug, Deserialize)]
struct BatteryConfig {
    raw_empty: u16,
    raw_full: u16,
    empty_mv: u16,
    full_mv: u16,
    poll_seconds: u64,
}

fn main() {
    // esp-generate の Xtensa 用処理
    linker_be_nice();
    check_xtensa_linker_available();

    // presenter.toml -> Rust 定数
    generate_presenter_config();

    // 重要:
    // linkall.x は最後の linker script にする．
    println!("cargo:rustc-link-arg=-Tlinkall.x");
}

fn generate_presenter_config() {
    println!("cargo:rerun-if-changed=presenter.toml");

    let source = fs::read_to_string("presenter.toml").expect("failed to read presenter.toml");

    let config: Config = toml::from_str(&source).expect("invalid presenter.toml");

    let mouse = config.mouse;

    let keymap = config.keymap;

    let battery = config.battery;

    assert!(mouse.poll_hz > 0, "mouse.poll_hz must be greater than 0");

    assert!(
        battery.raw_full > battery.raw_empty,
        "battery.raw_full must be greater than battery.raw_empty"
    );

    assert!(
        battery.full_mv > battery.empty_mv,
        "battery.full_mv must be greater than battery.empty_mv"
    );

    assert!(
        battery.poll_seconds > 0,
        "battery.poll_seconds must be greater than 0"
    );

    assert!(
        (0..127).contains(&mouse.dead_zone),
        "mouse.dead_zone must be in 0..127"
    );

    assert!(
        mouse.base_speed_px_per_sec > 0.0,
        "mouse.base_speed_px_per_sec must be greater than 0"
    );

    assert!(
        mouse.max_speed_px_per_sec >= mouse.base_speed_px_per_sec,
        "mouse.max_speed_px_per_sec must be greater than or equal to mouse.base_speed_px_per_sec"
    );

    assert!(
        mouse.gain_rise_per_sec > 0.0,
        "mouse.gain_rise_per_sec must be greater than 0"
    );

    assert!(
        mouse.gain_fall_per_sec > 0.0,
        "mouse.gain_fall_per_sec must be greater than 0"
    );

    assert!(
        (0.0..=1.0).contains(&mouse.curve_weight),
        "mouse.curve_weight must be in 0.0..=1.0"
    );

    assert!(
        (0.0..=1.0).contains(&mouse.smoothing),
        "mouse.smoothing must be in 0.0..=1.0"
    );

    let interval_us = 1_000_000 / mouse.poll_hz;

    // Q15 fixed-point.
    //
    // presenter.toml では 0.0..1.0 の小数で指定するが，
    // ESP32 上では浮動小数点を使わない．
    let curve_weight_q15 = (mouse.curve_weight * 32768.0).round() as i32;

    let smoothing_q15 = (mouse.smoothing * 32768.0).round() as i32;

    let base_speed = mouse.base_speed_px_per_sec.round() as i32;

    let max_speed = mouse.max_speed_px_per_sec.round() as i32;

    let gain_rise_q15 = (mouse.gain_rise_per_sec * 32768.0).round() as i32;

    let gain_fall_q15 = (mouse.gain_fall_per_sec * 32768.0).round() as i32;

    let button_a_key = keyboard_usage(&keymap.button_a);

    let button_b_key = keyboard_usage(&keymap.button_b);

    let generated = format!(
        r#"
// This file is automatically generated by build.rs.
// Do not edit manually.

pub const MOUSE_POLL_HZ: i64 = {poll_hz};
pub const MOUSE_POLL_INTERVAL_US: u64 = {interval_us};

pub const MOUSE_DEAD_ZONE: i32 = {dead_zone};
pub const MOUSE_BASE_SPEED_PX_PER_SEC: i32 = {base_speed};
pub const MOUSE_MAX_SPEED_PX_PER_SEC: i32 = {max_speed};
pub const MOUSE_GAIN_RISE_Q15_PER_SEC: i32 = {gain_rise_q15};
pub const MOUSE_GAIN_FALL_Q15_PER_SEC: i32 = {gain_fall_q15};

pub const MOUSE_CURVE_WEIGHT_Q15: i32 = {curve_weight_q15};
pub const MOUSE_SMOOTHING_Q15: i32 = {smoothing_q15};

pub const MOUSE_INVERT_X: bool = {invert_x};
pub const MOUSE_INVERT_Y: bool = {invert_y};

pub const BUTTON_A_KEY: u8 = {button_a_key:#04x};
pub const BUTTON_B_KEY: u8 = {button_b_key:#04x};

pub const BATTERY_RAW_EMPTY: u16 = {battery_raw_empty};
pub const BATTERY_RAW_FULL: u16 = {battery_raw_full};

pub const BATTERY_EMPTY_MV: u16 = {battery_empty_mv};
pub const BATTERY_FULL_MV: u16 = {battery_full_mv};

pub const BATTERY_POLL_SECONDS: u64 = {battery_poll_seconds};
"#,
        poll_hz = mouse.poll_hz,
        interval_us = interval_us,
        dead_zone = mouse.dead_zone,
        base_speed = base_speed,
        max_speed = max_speed,
        gain_rise_q15 = gain_rise_q15,
        gain_fall_q15 = gain_fall_q15,
        curve_weight_q15 = curve_weight_q15,
        smoothing_q15 = smoothing_q15,
        invert_x = mouse.invert_x,
        invert_y = mouse.invert_y,
        button_a_key = button_a_key,
        button_b_key = button_b_key,
        battery_raw_empty = battery.raw_empty,
        battery_raw_full = battery.raw_full,
        battery_empty_mv = battery.empty_mv,
        battery_full_mv = battery.full_mv,
        battery_poll_seconds = battery.poll_seconds,
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is not set"));

    let output = out_dir.join("presenter_config.rs");

    fs::write(&output, generated).expect("failed to write presenter_config.rs");

    println!(
        "cargo:warning=generated presenter config: {}",
        output.display()
    );
}

fn keyboard_usage(name: &str) -> u8 {
    match name {
        "RightArrow" => 0x4f,
        "LeftArrow" => 0x50,
        "PageDown" => 0x4e,
        "PageUp" => 0x4b,
        "Space" => 0x2c,
        "Enter" => 0x28,
        "Escape" => 0x29,
        "F5" => 0x3e,
        other => panic!("unknown key: {other}"),
    }
}

// -----------------------------------------------------------------------------
// ESP32 / Xtensa linker support
//
// The functions below are based on the esp-generate Xtensa project template.
// -----------------------------------------------------------------------------

#[cfg(unix)]
fn check_xtensa_linker_available() {
    println!("cargo:rerun-if-env-changed=PATH");

    let target = env::var("TARGET").unwrap_or_default();

    println!(
        "cargo:rerun-if-env-changed={}",
        cargo_linker_env_var(&target)
    );

    let linker = xtensa_linker(&target);

    let error = match std::process::Command::new(&linker)
        .arg("--version")
        .output()
    {
        Ok(_) => return,
        Err(error) => error,
    };

    let export_file = env::var("HOME")
        .map(|home| format!("{home}/export-esp.sh"))
        .unwrap_or_else(|_| "$HOME/export-esp.sh".to_string());

    panic!(
        "Xtensa linker `{linker}` was not found in PATH \
         or could not be executed: {error}.\n\n\
         Xtensa targets on Unix require espup's environment \
         export file to be sourced before building.\n\
         Try: `source {export_file}`\n\n\
         If the export file does not exist, \
         run `espup install` first."
    );
}

#[cfg(not(unix))]
fn check_xtensa_linker_available() {}

#[cfg(unix)]
fn xtensa_linker(target: &str) -> String {
    if let Some(linker) = cargo_configured_linker(target) {
        return linker;
    }

    target
        .strip_prefix("xtensa-")
        .and_then(|target| target.strip_suffix("-none-elf"))
        .map(|chip| format!("xtensa-{chip}-elf-gcc"))
        .unwrap_or_else(|| "xtensa-esp32-elf-gcc".to_string())
}

#[cfg(unix)]
fn cargo_configured_linker(target: &str) -> Option<String> {
    env::var(cargo_linker_env_var(target)).ok()
}

#[cfg(unix)]
fn cargo_linker_env_var(target: &str) -> String {
    let target = target.replace('-', "_").to_ascii_uppercase();

    format!("CARGO_TARGET_{target}_LINKER")
}

fn linker_be_nice() {
    let args: Vec<String> = env::args().collect();

    if args.len() > 2 {
        let kind = &args[1];
        let what = &args[2];

        match kind.as_str() {
            "undefined-symbol" => match what.as_str() {
                "_stack_start" => {
                    eprintln!();
                    eprintln!("linkall.x may be missing");
                    eprintln!();
                }

                what if what.starts_with("esp_rtos_") => {
                    eprintln!();
                    eprintln!(
                        "esp-radio has no scheduler enabled. \
                             Make sure esp-rtos is initialized."
                    );
                    eprintln!();
                }

                "free"
                | "malloc"
                | "calloc"
                | "get_free_internal_heap_size"
                | "malloc_internal"
                | "realloc_internal"
                | "calloc_internal"
                | "free_internal" => {
                    eprintln!();
                    eprintln!(
                        "esp-alloc may be missing \
                             or incorrectly configured"
                    );
                    eprintln!();
                }

                _ => {}
            },

            _ => {
                std::process::exit(1);
            }
        }

        std::process::exit(0);
    }

    // Xtensa linker の診断をこの build.rs へ戻す．
    println!(
        "cargo:rustc-link-arg=-Wl,--error-handling-script={}",
        env::current_exe().unwrap().display()
    );
}
